apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx-service
  namespace: default
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx
  type: NodePort

